scaffold react app
dxe/adb pull request #214
Opened 2024-12-28 01:52 UTC by jakehobbs

2024-12-28 09:00 UTC, alexsapps approved these changes
If you are up to it, would be nice for the commit message to include the command you used to create this scaffolding so we can see any options that vary from the default and cross reference our code with the output of that command for future debugging needs. But not super necessary.

2024-12-28 09:00 UTC, alexsapps commented on frontend-v2/README.md
> +yarn dev
delete these non-npm options (if we are going to stick with npm)? would be nice to keep the README relevant.

2025-01-09 22:45 UTC, jakehobbs commented on Makefile
> +    (cd frontend && nvm install 16 && npm run dev-build) && \
This is kinda annoying. But we have some super old deps in the Vue app that break if we go past Node 16. But we need at least 18 to use the latest React.

2025-01-09 22:45 UTC, jakehobbs commented on frontend/ActivistList.vue
> +        this.view === 'all_activists' || this.view === 'leaderboard' ? initialDateFromValue() : '',
bug fix

2025-01-09 22:45 UTC, jakehobbs commented on frontend/ChapterList.vue
> +      this.currentChapter = !chapter ? ({} as Chapter) : { ...chapter };
these were just some small changes to make TS compiler happy

2025-01-09 22:45 UTC, jakehobbs commented on frontend/UserList.vue
> +  disabled: boolean;
this should have always been here, but it was missing

2025-01-09 22:45 UTC, jakehobbs commented on frontend/nav.json
> +{
i moved the menu data here in anticipation of creating a navbar component in react, so that we can share the data b/w react & vue.

2025-01-09 22:45 UTC, jakehobbs commented on server/src/main.go
> +	router.Handle("/static_resources_hash", alice.New(main.corsAllowGetMiddleware).ThenFunc(main.StaticResourcesHashHandler))
not the biggest fan of this, but i think it's fine for now

2025-01-09 23:39 UTC, alexsapps requested changes

2025-01-09 23:39 UTC, alexsapps commented on frontend-v2/src/components/ContentWrapper.tsx
> +export const ContentWrapper = (props: {
could add a comment explaining the motivation or saying what this does exactly. does it just add visual padding, and is it intended to wrap all of the content on a page or just anywhere padding is needed?

2025-01-09 23:39 UTC, alexsapps commented on frontend-v2/src/components/VueNavbar.tsx
> +// for more seamless UX. Once most pages are rebuilt in
could you explain the seamless ux part? what is the implied alternative that would be less seamless?

also wondering how the vue navbar works in this context. do its links go to the vue app or stay in the react app? does it load vue components in react?

2025-01-09 23:39 UTC, alexsapps commented on Makefile
> +    (cd frontend && nvm install 16 && npm run dev-build) && \
that would be useful to add as a comment

// As of January 2025, upgrading past Node 16 breaks old Vue dependencies, and Node 18 is required to use the latest version of React.

2025-01-09 23:39 UTC, alexsapps commented on frontend-v2/README.md
Could you explain at a high level how this migration is set up? The context would help me review.

Some questions I have:
* Does this share auth cookies with the Vue frontend or do they sign into both apps?
* Is the app intended to be served from the same subdomain or another one?
* How are Vue components loaded in? How does the navigation work? Can users see both versions of pages at different URLs or do new pages replace old pages?

2025-01-09 23:39 UTC, alexsapps commented on frontend-v2/src/hooks/use-static-resource-hash.ts
> +// This is only used for Vue components and should eventually be removed.
in case we need to look back a long time from now (even though it's more temporary than other code), could you explain what this does too? if it's some technique you found online, could be helpful to link to the source.

2025-01-09 23:39 UTC, alexsapps commented on frontend/ChapterList.vue
> +      this.currentChapter = !chapter ? ({} as Chapter) : { ...chapter };
is making it an optional parameter also necessary for the ts compiler? if the old code was working, it seems to imply that the args passed were always non-nullish.
and is this not only necessary when the parameter is optional?

but since this code should hopefully be getting deleted soon, feel free to ignore if it takes non-trivial looking into :)

2025-01-10 04:53 UTC, jakehobbs commented on frontend/ChapterList.vue
> +      this.currentChapter = !chapter ? ({} as Chapter) : { ...chapter };
We are calling it in places with only 1 param, so it should be optional unless we change that.

2025-01-10 04:54 UTC, jakehobbs commented on frontend-v2/src/components/ContentWrapper.tsx
> +export const ContentWrapper = (props: {
sure, it just does the same thing as the "body wrapper" from the vue app

2025-01-10 04:56 UTC, jakehobbs commented on frontend-v2/src/components/VueNavbar.tsx
> +// for more seamless UX. Once most pages are rebuilt in
seamless b/c the navbar looks the same on all pages (vue and react), and doesn't require us changing the code in 2 places. as opposed to alternative of having 2 navbars that look different when you navigate b/w the react pages & the vue pages.

the vue navbar within the react app goes to the vue pages still like it always has.

2025-01-10 05:00 UTC, jakehobbs commented on frontend-v2/README.md
auth is handled the same way as always. (it's actually mostly handled server-side and in vanilla js, not within the vue components.)

the react app is served at all `/v2/*` paths for now (via a proxy in local dev so the next.js dev server can properly run, then via static files in the prod build).

vue pages & navigation work exactly the same as they always have. just if a user goes to a `/v2` page, it loads the react app. one a new page is ready, it will replace an old page (incrementally).

2025-01-10 05:02 UTC, jakehobbs commented on frontend-v2/src/hooks/use-static-resource-hash.ts
> +// This is only used for Vue components and should eventually be removed.
using it like we use it in other places in the codebase, just added a new endpoint to fetch it w/o doing the go template SSR stuff since the react code is not doing any SSR.

2025-01-10 21:16 UTC, alexsapps approved these changes
Approving in case we decide to add comments in a separate PR or if you want me to add the comments.

2025-01-10 21:16 UTC, alexsapps commented on frontend-v2/src/components/ContentWrapper.tsx
> +export const ContentWrapper = (props: {
i'm not familiar with the body wrapper but since we're getting rid of it, might be good to explain it as visual padding intended for the content of whole pages minus navigation and site-wide boilerplate, if that's accurate.

2025-01-10 21:16 UTC, alexsapps commented on frontend-v2/src/hooks/use-static-resource-hash.ts
> +// This is only used for Vue components and should eventually be removed.
i'm still confused what it does. if this is accurate, perhaps you could specify it "// Loads static HTML resources from the backend server for server-side rendering in Vue components" ?

2025-01-10 21:16 UTC, alexsapps commented on frontend/ChapterList.vue
> +      this.currentChapter = !chapter ? ({} as Chapter) : { ...chapter };
oh my bad, AI lied to me {...undefined} does not throw an error.

2025-01-10 21:16 UTC, alexsapps commented on frontend-v2/README.md
oh okay. sounds like /v2/* starts out as basically the same as the original app, although it is an independent frontend except for auth and any other vanilla JS, and its pages will be incrementally converted to react, but the vue pages will remain available at their current locations.

2025-01-10 21:16 UTC, alexsapps commented on frontend-v2/src/components/ui/button.tsx
did we hand-write all this, or if there are any instructions to generate more of these maybe we could explain in a /ui/README.md with just a link to whatever like https://www.radix-ui.com/ ?

2025-01-10 21:16 UTC, alexsapps commented on frontend-v2/src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]) {
what does CN stand for? would be nice to have a comment that introduces this function without having to infer from usage / dig into the dependencies' docs, however briefly. no need to explain everything completely since it's obviously just wrapping something else.

2025-01-20 18:40 UTC, jakehobbs commented on frontend-v2/src/hooks/use-static-resource-hash.ts
> +// This is only used for Vue components and should eventually be removed.
it just gets a random hash that is re-generated whenever the server restarts. will explain more in comment.

2025-01-20 18:41 UTC, jakehobbs commented on frontend-v2/src/components/ui/button.tsx
the components in the `ui` directory are initially generated by shadcn. will note in the readme.

2025-01-20 18:43 UTC, jakehobbs commented on frontend-v2/src/components/ui/button.tsx
https://ui.shadcn.com/docs

2025-01-20 18:45 UTC, jakehobbs commented on frontend-v2/src/lib/utils.ts
> +export function cn(...inputs: ClassValue[]) {
this util is generated by shadn. i'll add a link to an explanation of it.

2025-01-20 23:35 UTC, merged